monolog:
  handlers:
    telebot_debug_logger:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%/telebot/debug.log"
      level: debug
      max_files: 10
      channels: [ "telebot_debug" ]
    telebot_updates_logger:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%/telebot/updates.log"
      level: info
      max_files: 10
      channels: [ "telebot_updates" ]
    main:
      type: rotating_file
      level: notice
      path: "%kernel.logs_dir%/%kernel.environment%/main/main.log"
      max_files: 10
      channels: [ "!telebot_debug" , "!telebot_updates"]

  channels:
    - telebot_debug
    - telebot_updates