services:
    processing.log.processor.pid:
        class: Monolog\Processor\ProcessIdProcessor
        tags:
            - { name: monolog.processor }
    formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "---------------------------------------------------------------------------------------------\n
            [PID:%%extra.process_id%%] [%%datetime%%] [%%level_name%%] [CHANNEL:%%channel%%] %%message%% [CONTEXT:%%context%%]\n"

monolog:
    handlers:
        main:
            type: rotating_file
            path: "log/info.log"
            max_files: 10
            level: info
            formatter: formatter
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
            formatter: formatter
