monolog:
  handlers:
    telebot:
      type: stream
      path: "%telebot_log_dir%/telebot.log"
      formatter: monolog.my_line_formatter
      channels: [ "telebot" ]
    main:
      type: console
      process_psr_3_messages: false
      channels: [ "!telebot" ]

  channels:
    - telebot