version: '3.5'
services:
  superintegrator:
    container_name: c-superintegrator
    build: ./images
    user: app
    environment:
      XDEBUG_CONFIG: "remote_host=172.20.0.1 remote_port=9011"
      PHP_IDE_CONFIG: serverName=xdebug_server
    restart: always
    working_dir: '/var/www/superintegrator'
    extra_hosts:
      - super.test:172.20.0.1
    volumes:
      - ./../:/var/www/superintegrator
    networks:
      default:
        ipv4_address: 172.20.0.2

networks:
  default:
    external:
      name: super_network

