version: '3.5'
services:
  superintegrator:
    container_name: c-superintegrator
    image: webdevops/php-dev:7.2
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST} remote_port=${XDEBUG_PORT}"
      XDEBUG_CLIENT_HOST: '${XDEBUG_HOST}'
      XDEBUG_CLIENT_PORT: '${XDEBUG_PORT}'
      PHP_IDE_CONFIG: serverName="xdebug_server"
    restart: always
    working_dir: '/var/www/superintegrator'
    extra_hosts:
      - super.test:${HOST}
    volumes:
      - ${APP_PATH}:/var/www/superintegrator
    networks:
      default:
        ipv4_address: 172.20.0.2

networks:
  default:
    external:
      name: super_network

