version: '3.7'

services:
  nginx:
    container_name: c-nginx-super
    image: nginx:alpine
    restart: always
    ports:
      - '81:80'
      - '444:443'
    volumes:
      - ./../:/var/www/superintegrator
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      default:
        ipv4_address: 172.20.0.3

networks:
  default:
    external:
      name: super_network