services:
  command.base_daemon:
    class: App\Commands\BaseDaemon
    abstract: true
    arguments:
      - '@monolog.logger'

  command.create_user:
    class: App\Commands\CreateUserCommand
    arguments:
      - '%env(APP_SECRET)%'
      - '@doctrine.orm.entity_manager'

  command.delete_user:
    class: App\Commands\DeleteUserCommand
    arguments:
      - '@repository.user_role'
      - '@doctrine.orm.entity_manager'

  command.telebot.conversation.my_keys:
    class: App\Commands\TeleBot\Conversation\MyKeysCommand
    arguments:
      - '@repository.telebot_key'
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: telebot.command, command: mykeys }

  command.telebot.conversation.clear_chat:
    class: App\Commands\TeleBot\Conversation\ClearChatCommand
    tags:
      - { name: telebot.command, command: clearchat }