services:
  command.base_daemon:
    class: App\Commands\BaseDaemon
    abstract: true
    arguments:
      - '@monolog.logger'

  command.api_data_fetcher:
    class: App\Commands\ApiFetcher\ApiDataFetcherCommand
    abstract: true
    arguments:
      - '@repository.archive'

  command.sender:
    class: App\Commands\SenderCommand
    parent: 'command.base_daemon'
    arguments:
      - '@monolog.logger'
      - '@tools.cityads_postbck_manager'
      - '@app.service.sender.message_manager'
    tags:
      - { name: console.command }

  command.fonbet_data_fetcher:
    class: App\Commands\ApiFetcher\FonbetApiDataFetcher
    parent: 'command.api_data_fetcher'
    tags:
      - { name: console.command }

  command.affise_export:
    class: App\Commands\Fonbet\AffiseExportCommand
    parent: 'command.base_daemon'
    arguments:
      - '@monolog.logger'
      - '@repository.message'
      - '@repository.archive'
    tags:
      - { name: console.command }