services:
  command.base_daemon:
    class: App\Commands\BaseDaemon
    abstract: true

  command.sender:
    class: App\Commands\SenderCommand
    parent: 'command.base_daemon'
    arguments:
      - '@service.sender'
    tags:
      - { name: console.command }

  command.pull:
    class: App\Commands\PullApiDataCommand
    parent: 'command.base_daemon'
    arguments:
          - '@service.api_data_fetcher'
          - '@orm.model.archive'
    tags:
      - { name: console.command }

#  command.test:
#    class: App\Commands\TestCommand
#    arguments:
#      - '@service.postback_collector'
#      - '@service.sender'
#    tags:
#      - { name: console.command }