services:
  cron_command:
    class: App\Commands\CronCommand
    arguments:
      - '@service_factory'
      - '@monolog.logger'
    tags:
      - { name: console.command }

  test_command:
    class: App\Commands\TestCommand
    arguments:
      - '@postback_collector'
      - '@sender'
    tags:
      - { name: console.command }

  pull_command:
    class: App\Commands\PullApiDataCommand
    arguments:
      - '@api_data_fetcher'
    tags:
      - { name: console.command }