services:
  command.base_daemon:
    class: App\Commands\BaseDaemon
    abstract: true

  command.api_data_fetcher:
    class: App\Commands\ApiFetcher\ApiDataFetcherCommand
    abstract: true
    arguments:
      - '@orm.model.archive'
      - '@monolog.logger'

  command.sender:
    class: App\Commands\SenderCommand
    parent: 'command.base_daemon'
    arguments:
      - '@service.sender'
    tags:
      - { name: console.command }

  command.fonbet_data_fetcher:
    class: App\Commands\ApiFetcher\FonbetApiDataFetcher
    parent: 'command.api_data_fetcher'
    tags:
      - { name: console.command }

  command.affise_export:
    class: App\Commands\Fonbet\AffiseExportCommand
    parent: 'command.base_daemon'
    arguments:
      - '@orm.model.message'
      - '@orm.model.archive'
    tags:
      - { name: console.command }

#  command.test:
#    class: App\Commands\TestCommand
#    arguments:
#      - '@service.postback_collector'
#      - '@service.sender'
#    tags:
#      - { name: console.command }