services:
  command.base_daemon:
    class: App\Commands\BaseDaemon
    abstract: true
    arguments:
      - '@monolog.logger'

  command.create_user:
    class: App\Commands\CreateUserCommand
    arguments:
      - '%env(APP_SECRET)%'
      - '@doctrine.orm.entity_manager'

  command.delete_user:
    class: App\Commands\DeleteUserCommand
    arguments:
      - '@repository.user_role'
      - '@doctrine.orm.entity_manager'
      -
  command.keys_fetch:
    class: App\Commands\KeysFetchCommand
    arguments:
      - '@repository.telebot_key'
    tags:
      - { name: console.command, command: keys:fetch }

  command.telebot.conversation.conversation_command:
    class: App\Commands\TeleBot\Conversation\ConversationCommand
    abstract: true
    arguments:
      $dispatcher: '@event_dispatcher'

  command.telebot.conversation.my_keys:
    class: App\Commands\TeleBot\Conversation\MyKeysCommand
    parent: command.telebot.conversation.conversation_command
    arguments:
      $keyRepo: '@repository.telebot_key'
      $entityManager: '@doctrine.orm.entity_manager'
    tags:
      - { name: telebot.command, command: mykeys }

  command.telebot.conversation.cancel:
    parent: command.telebot.conversation.conversation_command
    class: App\Commands\TeleBot\Conversation\CancelCommand
    arguments:
      $conversationRepository: '@repository.conversation'
    tags:
      - { name: telebot.command, command: cancel }