services:
  cron_command:
    class: App\Commands\CronCommand
    arguments:
      - '@service_factory'
    tags:
      - { name: console.command }

  test_command:
    class: App\Commands\TestCommand
    arguments:
      - '@postback_collector'
      - '@sender'
    tags:
      - { name: console.command }