services:
  app.controller.tool:
    class: App\Controller\ToolController
    tags: ['controller.service_arguments']
    arguments:
      - '@monolog.logger'
      - '@tools.collection'
      - '%kernel.environment%'

  app.controller.blog:
    class: App\Controller\BlogController
    tags: ['controller.service_arguments']
    arguments:
      - '@repository.post'

  app.controller.telebot:
    class: App\Controller\TelebotController
    tags: ['controller.service_arguments']
    arguments:
      - '@app.services.telebot.processor'