services:
  app.controller.tool:
    class: App\Controller\ToolController
    arguments:
      $logger: '@monolog.logger'
      $tools: '@tools.collection'

  app.controller.blog:
    class: App\Controller\BlogController
    arguments:
      - '@repository.post'

  app.controller.telebot:
    class: App\Controller\TelebotController
    arguments:
      - '@app.service.telebot.processor'
      - '@monolog.logger'