services:
  orm.model.message:
    class: App\Orm\Model\Message
    arguments:
      - '@doctrine.orm.entity_manager'

  orm.model.archive:
    class: App\Orm\Model\Archive
    arguments:
      - '@doctrine.orm.entity_manager'