parameters:
  telebot.commands_dir: '%kernel.root_dir%/Commands/TeleBot/Conversation'
  telebot.url: 'https://api.telegram.org/bot{token}/{action}'
  telebot.token: '%env(BOT_TOKEN)%'
  telebot.allow_users: '%env(BOT_ALLOW_USERS)%'
  telebot.admin: '%env(int:BOT_ADMIN)%'

  database.host: '%env(key:host:url:DATABASE_URL)%'
  database.user: '%env(key:user:url:DATABASE_URL)%'
  database.password: '%env(key:pass:url:DATABASE_URL)%'
  database.database_name: '%env(key:path:url:DATABASE_URL)%'
