services:
  repository.base:
    class: App\Repository\BaseRepository
    abstract: true
    arguments:
      - '@doctrine'
      - '@monolog.logger'

  repository.post:
    class: App\Repository\PostRepository
    parent: 'repository.base'

  repository.message:
    class: App\Repository\MessageRepository
    parent: 'repository.base'

  repository.csv_file:
    class: App\Repository\CsvFileRepository
    parent: 'repository.base'

  repository.archive:
    class: App\Repository\ArchiveRepository
    parent: 'repository.base'

  repository.test_xml:
    class: App\Repository\TestXmlRepository
    parent: 'repository.base'

  repository.user_role:
    class: App\Repository\UserRoleRepository
    arguments:
      - '@doctrine'
      - '@monolog.logger'

  repository.history:
    class: App\Repository\HistoryRepository
    arguments:
      - '@doctrine'

  repository.telebot_key:
    class: App\Repository\TelebotKeyRepository
    arguments:
      - '@doctrine'