login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST

logout:
  path: /logout
  methods: GET

main_page:
  path: /
  controller: App\Controller\ToolController::renderMainPage

tools:
  path: /tools
  controller: App\Controller\ToolController::renderMainPage

tool.common:
  path: /tools/{tool}/{action}
  controller: App\Controller\ToolController::index
  requirements:
    action: 'new|update|list'
  defaults:
    tool: null
    action: null

tool.xml_page:
  path: /xml
  controller: App\Controller\ToolController::xmlPage

#telebot
telebot_api.index:
  path: /telebot
  controller: App\Controller\TelebotController::index

telebot_api.show_logs:
  path: /telebot/show_logs
  controller: App\Controller\TelebotController::showDebugLogs

telebot_api.clear_logs:
  path: /telebot/clear_logs
  controller: App\Controller\TelebotController::clearDebugLogs

telebot_api.set_hook:
  path: /telebot/set_hook
  controller: App\Controller\TelebotController::setHook

#logs
logs.show:
  path: /logs
  controller: App\Controller\LogsController::index

logs.clear:
  path: /logs/clear
  controller: App\Controller\LogsController::clear

# blog
blog:
  path: /blog/{page}
  controller: App\Controller\BlogController::list
  defaults:
    page: 1
  requirements:
    page: '\d+'

blog.post.new:
  path: /blog/post/new
  controller: App\Controller\BlogController::new
  defaults:
    page: /

blog.post.edit:
  path: /blog/post/{id}/edit
  controller: App\Controller\BlogController::new
  defaults:
    page: /

blog.post.delete:
  path: /blog/post/{id}/delete
  controller: App\Controller\BlogController::delete
  defaults:
    page: /

blog.post.save:
  path: /blog/post/save
  controller: App\Controller\BlogController::save
  defaults:
    page: /

blog.post.view:
  path: /blog/post/{slug}
  controller: App\Controller\BlogController::show_post