main_page:
  path: /
  controller: App\Controller\BaseController::mainPage

super_integrator.tool:
  path: /tools/{tool}
  controller: App\Controller\ToolController::index
  defaults:
    tool:

super_integrator.tools.tool.action:
  path: /tools/{tool}/{action}
  controller: App\Controller\ToolController::index
  defaults:
    tool:

# blog
blog.list:
  path: /blog/{page}
  controller: App\Controller\BlogController::list
  defaults:
    page: 1
  requirements:
    page: '\d+'

blog.post:
  path: /blog/post
  controller: App\Controller\BlogController::show_post

blog.post.new:
  path: /blog/new
  controller: App\Controller\BlogController::new
  defaults:
    page: /