index:
  path: /{page}
  controller: App\Controller\HttpController::index
  defaults:
    page: /

create_new:
  path: /{page}/new
  controller: App\Controller\HttpController::createNew
  defaults:
    page: /