page:
  path: /{page}
  controller: App\Controller\HttpController::index
  defaults:
    page: /

action:
  path: /{page}/{action}
  controller: App\Controller\HttpController::index
  defaults:
    page: /