main:
  methods: get
  path: /{page}
  controller: App\Controller\BaseController::main
  defaults:
    page: /

request:
  methods: post
  path: /
  controller: App\Controller\RequestController::handle