index:
  methods: get
  path: /{page}
  controller: App\Controller\HttpController::index
  defaults:
    page: /

request:
  methods: post
  path: /
  controller: App\Controller\RequestController::handle

#todo доделать
fileUpload:
  methods: post
  path: /fileUpload
  controller: App\Controller\RequestController::loadFilesOnServer