index:
  methods: get
  path: /{page}
  controller: App\Controller\PageController::index
  defaults:
    page: /

request:
  methods: post
  path: /
  controller: App\Controller\RequestController::handle

#todo доделать
fileUpload:
  methods: post
  path: /sender
  controller: App\Controller\RequestController::temporaryUploadAction