main:
  methods: get
  path: /
  controller: App\Controller\BaseController::main

geo_get:
  methods: get
  path: /geo
  controller: App\Controller\BaseController::geo

data_transformer:
  methods: get
  path: /data_transformer
  controller: App\Controller\BaseController::dataTransformer

ali_orders:
  methods: get
  path: /ali_orders
  controller: App\Controller\BaseController::aliOrders

sender:
  methods: get
  path: /sender
  controller: App\Controller\BaseController::sender

xml_emulator:
  methods: get
  path: /xml_emulator
  controller: App\Controller\BaseController::xmlEmulator


request:
  methods: post
  path: /
  controller: App\Controller\RequestController::handle