imports:
    - { resource: parameters.yaml }
    - { resource: repositories.yaml }
    - { resource: commands.yaml }
    - { resource: tools.yaml }
    - { resource: controllers.yaml }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $telebotProcessor: '@app.services.telebot.processor'
            $tools: '@tools.collection'
            $environment: '%kernel.environment%'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Services\Tools\:
        resource: '../src/Services/Tools'
        tags: [ 'tool' ]

    App\Repository\:
        resource: '../src/Repository'
        tags: [ 'doctrine.repository_service' ]

    app.security.access_denied_handler:
        class: App\Security\AccessDeniedHandler
        arguments:
            - '@twig'

    app.services.telebot.processor:
        class: App\Services\TeleBot\Processor
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@repository.conversation'
            - !tagged { tag: 'telebot.command', index_by: 'command' }
            - '%telebot.allow_users%'
            - '%telebot.token%'
            - '%telebot.name%'

    app.service.sender.message_manager:
        class: App\Services\Sender\MessageManager
        arguments:
            - '@repository.message'
            - '@monolog.logger'

    docktrine.common.cache.filesystem_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments:
            - '%kernel.logs_dir%/%kernel.environment%'