# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
    - { resource: parameters.yaml }
    - { resource: repositories.yaml }
    - { resource: commands.yaml }

services:
    - { resource: tools.yaml }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $env: '%environment%'
            $aliexpressApiUrl: '%ali_api_url%'
            $appDomain: '%app_domain%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Repositories,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
#    App\Controller\:
#        resource: '../src/Controller'
#        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.controller.tool:
        class: App\Controller\ToolController
        arguments:
            - '@monolog.logger'
            - '@app.service.super.geo_search'
            - '@app.service.super.xml_emulator'
            - '@app.service.super.cityads_postbck_manager'
            - '@app.service.super.ali_orders'
            - '@app.service.super.cryptor'

    app.controller.blog:
        class: App\Controller\BlogController
        arguments:
            - '@app.repository.post'

    app.service.sender.message_manager:
        class: App\Services\Sender\MessageManager
        arguments:
            - '@app.repository.message'
            - '@monolog.logger'

    app.service.app_fixture:
        class: App\DataFixtures\AppFixtures