imports:
    - { resource: parameters.yaml }
    - { resource: repositories.yaml }
    - { resource: commands.yaml }
    - { resource: tools.yaml }
    - { resource: controllers.yaml }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $env: '%env(APP_ENV)%'
            $domain: '%env(DOMAIN)%'
            $telebotLogDir: '%telebot_log_dir%'
            $telebotToken: '%env(BOT_TOKEN)%'
            $salt: '%env(APP_SECRET)%'
            $entityManager: '@doctrine.orm.entity_manager'
            $twig: '@twig'
            $userRepo: '@repository.user'
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Repositories,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Services\Tools\:
        resource: '../src/Services/Tools'
        tags: [ 'tool' ]

    App\Tests\DataFixtures\:
        resource: '../tests/DataFixtures'

    monolog.my_line_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments: [ null, null, true ]

    app.service.sender.message_manager:
        class: App\Services\Sender\MessageManager
        arguments:
            - '@repository.message'
            - '@monolog.logger'

    app.service.telebot.processor:
        class: App\Services\TeleBot\TelebotProcessor
        arguments:
            $client: '@app.http.client'
            $telebotLogger: '@monolog.logger'

    app.http.client:
        class: GuzzleHttp\Client